# Starter pipeline
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'PriyaAWS'
    regionName: 'us-east-1'
    stackName: 'EC2-1'
    templateSource: 'file'
    templateFile: 'ec2-instance-create.yml'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
