
# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'PriyaAWS'
    regionName: 'us-east-1'
    stackName: 'firstEC2'
    templateSource: 'url'
    templateUrl: 'https://github.com/clickclicksenthil/AWSResources/raw/main/ec2-instance-create.yml'
